"""Database connection helper utilities."""

from beartype import beartype
from beartype.typing import Any, Optional
from psycopg2 import connect
from psycopg2.extensions import connection, cursor

from src.domain.connection_info import ConnectionInfo
from src.interfaces.db.db_connection_interface import IDbConnection


class DbConnection(IDbConnection):
    """Database connection logic. This class initiates with an injection of
    the necessary credentials for connection with a 'psycopg2' database.

    This class takes on the responsibility of closing the connections after
    having used them up. It's ideal to use the objects generated by this class
    with the keyword 'with'.
    """

    @beartype
    def __init__(self, connection_info: ConnectionInfo) -> None:
        """Initializes connection helper from a 'ConnectionInfo' dataclass.

        Args:
            connection_info: A dataclass that provides the database
                connection parameters (dbname, user, password, host, port).

        Attributes:
            dbname (str): The name of the database.
            user (str): The name of the database user.
            password (str): The database password.
            host (str): The database host/server.
            port (str): The database connection port.
            cursor (Optional[cursor]): The cursor for queries.
            _connection (Optional[connection]): The connection for cursors.
        """
        self.dbname: str = connection_info.dbname
        self.user: str = connection_info.user
        self.password: str = connection_info.password
        self.host: str = connection_info.host
        self.port: str = connection_info.port
        self.cursor: Optional[cursor] = None
        self._connection: Optional[connection] = None

    @beartype
    def __exit__(self, *args: Any) -> None:
        """Close connection and cursor once they have been used.

        Args:
            *args: Any arguments passed at exit time.
        """
        if self.cursor:
            self.cursor.close()

        if self._connection:
            self._connection.close()

    @beartype
    def _create_connection(self) -> connection:
        """Opens a new database connection using psycopg2.

        Returns:
            connection: A new 'psycopg2' connection.
        """
        self._connection = connect(
            dbname=self.dbname,
            user=self.user,
            password=self.password,
            host=self.host,
            port=self.port,
        )

        self._connection.autocommit = True

        return self._connection

    @beartype
    def create_cursor(self) -> cursor:
        """Creates a database cursor from an existing connection.

        Returns:
            connection: A new 'psycopg2' cursor.
        """
        with self._create_connection() as connection:
            return connection.cursor()
